services:
  _defaults:
    autowire: true

  Kkos2\KkOs2DisplayIntegrationBundle\ExternalData\MultisiteCrawler:
  Kkos2\KkOs2DisplayIntegrationBundle\ExternalData\MultisiteHelper:
  Kkos2\KkOs2DisplayIntegrationBundle\ExternalData\DataFetcher:
  Kkos2\KkOs2DisplayIntegrationBundle\ExternalData\EventfeedHelper:
  Kkos2\KkOs2DisplayIntegrationBundle\ExternalData\BookbyenApiHelper:

  # Cron
  Kkos2\KkOs2DisplayIntegrationBundle\Cron\EventsSisCron:
    tags:
      - { name: kernel.event_subscriber }

  Kkos2\KkOs2DisplayIntegrationBundle\Cron\ColorfulMessageSisCron:
    tags:
      - { name: kernel.event_subscriber }

  Kkos2\KkOs2DisplayIntegrationBundle\Cron\EventplakatSisCron:
    tags:
      - { name: kernel.event_subscriber }

  Kkos2\KkOs2DisplayIntegrationBundle\Cron\CarouselSisCron:
    tags:
      - { name: kernel.event_subscriber }

  Kkos2\KkOs2DisplayIntegrationBundle\Cron\BookByenSisCron:
    tags:
      - { name: kernel.event_subscriber }
  Kkos2\KkOs2DisplayIntegrationBundle\Cron\TwoThreeVideoSisCron:
    tags:
      - { name: kernel.event_subscriber }
