parameters:

services:
  indholdskanalen_main.listener:
    class: Indholdskanalen\MainBundle\EventListener\SearchIndexer
    arguments: [@jms_serializer, @service_container, @indholdskanalen.utility_service]
    tags:
      - { name: doctrine.event_listener, event: postPersist }
      - { name: doctrine.event_listener, event: preUpdate }
      - { name: doctrine.event_listener, event: preRemove }

  indholdskanalen_main.serialization_listener:
    class: Indholdskanalen\MainBundle\EventListener\SerializationListener
    arguments: [@sonata.media.pool, @service_container, @indholdskanalen.template_service]
    tags:
      - { name: jms_serializer.event_subscriber}

  indholdskanalen.command.pushcontent:
    class: Indholdskanalen\MainBundle\Command\PushContentCommand
    tags:
      -  { name: console.command }

  indholdskanalen.template_service:
    class: Indholdskanalen\MainBundle\Services\TemplateService
    arguments: [@service_container]
    calls:
      - [ setContainer,[ @service_container ] ]

  indholdskanalen.koba_service:
    class: Indholdskanalen\MainBundle\Services\KobaService
    arguments: [%koba_path%, %koba_apikey%, @service_container]

  indholdskanalen.feed_service:
    class: Indholdskanalen\MainBundle\Services\FeedService
    arguments: [@service_container]

  indholdskanalen.instagram_service:
    class: Indholdskanalen\MainBundle\Services\InstagramService
    arguments: [@service_container]

  indholdskanalen.authentication_service:
    class: Indholdskanalen\MainBundle\Services\AuthenticationService
    arguments: [@service_container]

  indholdskanalen.sharing_service:
    class: Indholdskanalen\MainBundle\Services\SharingService
    arguments: [@jms_serializer, @service_container, @indholdskanalen.utility_service]
    tags:
      - { name: kernel.event_listener, event: indholdskanalen_sharing_service.add_channel_to_index, method: onAddChannelToIndex }
      - { name: kernel.event_listener, event: indholdskanalen_sharing_service.remove_channel_from_index, method: onRemoveChannelFromIndex }
      - { name: kernel.event_listener, event: indholdskanalen_sharing_service.update_channel, method: onUpdateChannel }

  indholdskanalen.utility_service:
    class: Indholdskanalen\MainBundle\Services\UtilityService
    arguments: [@indholdskanalen.authentication_service]

  indholdskanalen.middleware.communication:
    class: Indholdskanalen\MainBundle\Services\MiddlewareCommunication
    arguments: [@indholdskanalen.template_service, @indholdskanalen.utility_service]
    calls:
      - [ setContainer,[ @service_container ] ]

  indholdskanalen_main.api_authentication_service:
    class: Indholdskanalen\MainBundle\Security\ApiAuthenticationEntryPoint

  sonata.media.provider.zencoder:
    class: Indholdskanalen\MainBundle\Provider\ZencoderProvider
    tags:
      - { name: sonata.media.provider }
    arguments: [sonata.media.provider.zencoder, '@sonata.media.filesystem.local', '@sonata.media.cdn.server', '@sonata.media.generator.default', '@sonata.media.thumbnail.format', '%absolute_path_to_server%', '%zencoder_api%']
    calls:
      - [setTemplates, [{ helper_thumbnail: 'SonataMediaBundle:Provider:thumbnail.html.twig', helper_view: 'SonataMediaBundle:Provider:view_video.html.twig' }]]
