imports:
  - { resource: config_test.yml }

framework:
  profiler:
    collect: false
  translator:
    enabled: false

web_profiler:
  toolbar: false
  intercept_redirects: false

doctrine:
  dbal:
    dbname: "%database_name%_acceptance"
