imports:
    - { resource: config.yml }

framework:
    router:
        resource: '%kernel.project_dir%/app/config/routing_dev.yml'
        strict_requirements: true
    profiler: { only_exceptions: false }
    session:
        save_path: '/var/lib/php/sessions'

web_profiler:
    toolbar: '%debug_toolbar%'
    intercept_redirects: '%debug_redirects%'

monolog:
    channels: ['zencoder']
    handlers:
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
        zencoder:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.zencoder.log"
            level:  debug
            channels: [zencoder]
        console:
            type:   console
            bubble: false
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']
        server_log:
            type: server_log
            process_psr_3_messages: false
            host: 127.0.0.1:9911
