parameters:
  modules:
    busModule:
      files:
        - /apps/busModule/busModule.js
      dependencies:

    logModule:
      files:
        - /apps/logModule/services/logService.js
      dependencies:
        - busModule

    mainModule:
      files:
        - /apps/mainModule/controller/baseController.js
        - /apps/mainModule/services/apiService.js
        - /apps/mainModule/services/bodyService.js
        - /apps/mainModule/services/menuItemService.js
        - /apps/mainModule/services/searchService.js
        - /apps/mainModule/services/userService.js
      dependencies:

  bootstrap:
    modules:
      - logModule
      - mainModule
    services:
      - apiService
      - logService
      - userService
      - searchService
      - menuItemService
      - bodyService
