os2display_main:
  resource: "@Os2DisplayCoreBundle/Resources/config/routing.yml"
  prefix:   /

os2display_admin:
  resource: "@Os2DisplayAdminBundle/Resources/config/routing.yml"
  prefix:   /

JMSJobQueueBundle:
    resource: "@JMSJobQueueBundle/Controller/"
    type: annotation
    prefix: /admin/jobs

itk_koba_integration:
  resource: "@ItkKobaIntegrationBundle/Resources/config/routing.yml"
  prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_user_profile_show:
    path: /#/user

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
