_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml

_exchange:
    resource: "@ItkExchangeBundle/Resources/config/routing_dev.yml"
    prefix:   /

_itk_aarhus_data:
    resource: "@ItkAarhusDataBundle/Resources/config/routing_dev.yml"
    prefix:   /
