parameters:
  router.options.generator_base_class: Os2Display\CoreBundle\Routing\HashtagDecodedUrlGenerator

services:
  os2display.listener:
    class: Os2Display\CoreBundle\EventListener\SearchIndexer
    arguments: ['@jms_serializer', '@service_container', '@os2display.utility_service']
    tags:
      - { name: doctrine.event_listener, event: postPersist }
      - { name: doctrine.event_listener, event: postUpdate }
      - { name: doctrine.event_listener, event: postRemove }

  os2display.entity_service:
    class: Os2Display\CoreBundle\Services\EntityService
    arguments: ['@validator']

  os2display.group_manager:
    class: Os2Display\CoreBundle\Services\GroupManager
    arguments: ['@doctrine.orm.entity_manager', '@os2display.entity_service', '@service_container']

  os2display.grouping_listener:
    class: Os2Display\CoreBundle\EventListener\GroupingListener
    arguments: ['@service_container']
    tags:
      - { name: doctrine.event_subscriber }

  os2display.user_manager:
    class: Os2Display\CoreBundle\Services\UserManager
    arguments: ['@fos_user.user_manager', '@os2display.user_mailer_service', '@os2display.entity_service', '@fos_user.util.token_generator', '@os2display.security_manager']

  os2display.security_manager:
    class: Os2Display\CoreBundle\Services\SecurityManager
    arguments: ['@security.token_storage', '@doctrine.orm.entity_manager', '@security.access.decision_manager', '@security.role_hierarchy']

  os2display.api_data:
    class: Os2Display\CoreBundle\Services\ApiDataService
    arguments: ['@service_container']

  os2display.user_mailer_service:
    class: Os2Display\CoreBundle\Services\UserMailerService
    parent: fos_user.mailer.default
    public: true

  os2display.entity_manager:
    class: Os2Display\CoreBundle\Services\EntityManagerService
    arguments: ['@doctrine.orm.entity_manager', '@security.token_storage', '@security.authorization_checker']

  os2display.edit_voter:
    class: Os2Display\CoreBundle\Security\EditVoter
    arguments: ['@doctrine.orm.entity_manager', '@security.access.decision_manager', '@os2display.security_manager']
    public: false
    tags:
      - { name: security.voter }

  os2display.user_converter:
    class: Os2Display\CoreBundle\Request\ParamConverter\UserConverter
    arguments: ['@?doctrine', '@security.token_storage']
    tags:
      - { name: request.param_converter, priority: 1, converter: user_converter }

  os2display.api_authentication_service:
    class: Os2Display\CoreBundle\Security\ApiAuthenticationEntryPoint

  os2display.serialization_listener:
    class: Os2Display\CoreBundle\EventListener\SerializationListener
    arguments: ['@sonata.media.pool', '@service_container', '@os2display.template_service']
    tags:
      - { name: jms_serializer.event_subscriber}

  os2display.command.pushcontent:
    class: Os2Display\CoreBundle\Command\PushContentCommand
    tags:
      -  { name: console.command }

  os2display.template_service:
    class: Os2Display\CoreBundle\Services\TemplateService
    arguments: ['@service_container']

  os2display.feed_service:
    class: Os2Display\CoreBundle\Services\FeedService
    arguments: ['@service_container']
    tags:
      - { name: kernel.event_listener, event: ik.cron, method: onCron }

  os2display.authentication_service:
    class: Os2Display\CoreBundle\Services\AuthenticationService
    arguments: ['@service_container']

  os2display.sharing_service:
    class: Os2Display\CoreBundle\Services\SharingService
    arguments: ['@jms_serializer', '@service_container', '@os2display.utility_service']
    tags:
      - { name: kernel.event_listener, event: os2Display_sharing_service.add_channel_to_index, method: onAddChannelToIndex }
      - { name: kernel.event_listener, event: os2Display_sharing_service.remove_channel_from_index, method: onRemoveChannelFromIndex }
      - { name: kernel.event_listener, event: os2Display_sharing_service.update_channel, method: onUpdateChannel }
      - { name: kernel.event_listener, event: ik.cron, method: onCron }

  os2display.utility_service:
    class: Os2Display\CoreBundle\Services\UtilityService
    arguments: ['@os2display.authentication_service']

  os2display.middleware.communication:
    class: Os2Display\CoreBundle\Services\MiddlewareCommunication
    arguments: ['@service_container', '@os2display.template_service', '@os2display.utility_service']
    tags:
      - { name: kernel.event_listener, event: ik.cron, method: onCron, priority: 1 }

  sonata.media.provider.zencoder:
    class: Os2Display\CoreBundle\Provider\ZencoderProvider
    tags:
      - { name: sonata.media.provider }
    arguments: ['sonata.media.provider.zencoder', '@sonata.media.filesystem.local', '@sonata.media.cdn.server', '@sonata.media.generator.default', '@sonata.media.thumbnail.format', '%absolute_path_to_server%', '%zencoder_api%', '@logger']
    calls:
      - [setTemplates, [{ helper_thumbnail: 'SonataMediaBundle:Provider:thumbnail.html.twig', helper_view: 'SonataMediaBundle:Provider:view_video.html.twig' }]]
